### PR TITLE
Added CI tests

### PR DESCRIPTION
**Pull request by chrisgorgo**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Given the error, it seems to me that the data is not in the format that we used to develop this app.

**Comment by chrisgorgo** [comment]
This is the same downsampled dataset you sent me:

```
$ tar xvf ds005-deriv-light.tar
ds005-deriv-light/
ds005-deriv-light/derivatives/
ds005-deriv-light/derivatives/sub-01/
ds005-deriv-light/derivatives/sub-01/anat/
ds005-deriv-light/derivatives/sub-01/anat/sub-01_T1w_bmask_mni.nii.gz
ds005-deriv-light/derivatives/sub-01/anat/sub-01_T1w_tpm_mni0000.nii.gz
ds005-deriv-light/derivatives/sub-01/anat/sub-01_T1w_tpm_mni0001.nii.gz
ds005-deriv-light/derivatives/sub-01/anat/sub-01_T1w_tpm_mni0002.nii.gz
ds005-deriv-light/derivatives/sub-01/func/
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-01_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-01_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-01_bold_hmc_mni_bmask.nii.gz
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-02_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-02_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-02_bold_hmc_mni_bmask.nii.gz
ds005-deriv-light/derivatives/sub-02/
ds005-deriv-light/derivatives/sub-02/anat/
ds005-deriv-light/derivatives/sub-02/anat/sub-02_T1w_bmask_mni.nii.gz
ds005-deriv-light/derivatives/sub-02/anat/sub-02_T1w_tpm_mni0000.nii.gz
ds005-deriv-light/derivatives/sub-02/anat/sub-02_T1w_tpm_mni0001.nii.gz
ds005-deriv-light/derivatives/sub-02/anat/sub-02_T1w_tpm_mni0002.nii.gz
ds005-deriv-light/derivatives/sub-02/func/
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-01_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-01_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-01_bold_hmc_mni_bmask.nii.gz
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-02_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-02_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-02/func/sub-02_task-mixedgamblestask_run-02_bold_hmc_mni_bmask.nii.gz
ds005-deriv-light/derivatives/sub-03/
ds005-deriv-light/derivatives/sub-03/anat/
ds005-deriv-light/derivatives/sub-03/anat/sub-03_T1w_bmask_mni.nii.gz
ds005-deriv-light/derivatives/sub-03/anat/sub-03_T1w_tpm_mni0000.nii.gz
ds005-deriv-light/derivatives/sub-03/anat/sub-03_T1w_tpm_mni0001.nii.gz
ds005-deriv-light/derivatives/sub-03/anat/sub-03_T1w_tpm_mni0002.nii.gz
ds005-deriv-light/derivatives/sub-03/func/
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-01_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-01_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-01_bold_hmc_mni_bmask.nii.gz
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-02_bold_hmc.tsv
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-02_bold_hmc_mni.nii.gz
ds005-deriv-light/derivatives/sub-03/func/sub-03_task-mixedgamblestask_run-02_bold_hmc_mni_bmask.nii.gz
```

**Comment by chrisgorgo** [comment]
I've added read-only containers and tag based docker hub versioning.

**Comment by GaelVaroquaux** [comment]
One of the problems is that the CI doesn't run. It failed in your PR for an obscure reason that I don't understand:
https://circleci.com/gh/BIDS-Apps/rs_signal_extract/3

I restarted it this morning, as they were some SSL problems and I was hoping that it would go away, but we had another web failure: https://circleci.com/gh/BIDS-Apps/rs_signal_extract/4
I wonder if this failure is fully reproducible: if I try to connect myself to the googledrive URL, I get a 502 error often but not always.

Not sure what the best approach here. It seems that googledrive is not reliable. For nilearn we have been relying on NITRC storage that is on amazon. It's been very reliable. I don't know if the issues with googledrive are temporary or more long term. https://support.google.com/drive/answer/2456903?hl=en seems to say that it's temporary. I've tried for the last 10mn. I'll come back to it.

**Comment by GaelVaroquaux** [comment]
OK. It ran. I am now left with the joy of debugging problems when all my debugging tools are no longer usable :$

**Comment by GaelVaroquaux** [comment]
Closing in favor of #4

**Pull request closed without merging**
